### ISSUE TITLE
Lesson 01: Kubernetes Architecture & Troubleshooting - Update

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#2]
This video starts with a comment around having deployed an application. I know we're re-using content where possible, but how difficult would it be to clone this video and remove the intro? 

We can certainly just add a note that 'This video is being repurposed from another course, so the intro is not applicable" as well.

Feel free to delete this issue if this is not worth the effort at this stage.

**Comment by djschny** [comment]
Initially we were trying not to duplicate topics/knowledge and work off the basis of “CKA level of knowledge” hence why we left those two prior to this off.  IMO we have some options too:

* include the first two labs but not the lectures (since more connection there)
* include all 4 lessons (2 lectures / 2 labs) and document that they can be skipped/skimmed if they feel they aren’t getting any value
* Include links to the first two lecture/lab combos but not call them out as individual lessons

In regards to editing the video, there are other lessons and other places through this first version where the same occurs. IMO we should wait for initial round of feedback and continue on the "good enough" request from before.
