### ISSUE TITLE
The order of demos in course doesn't match the information shared in video

### ISSUE THREAD

**Issue by osmanchien** [vmware-tanzu-learning/tko-ref-arch-training#29]
**Describe the issue**
A minor issue I can see when walking through the “Introduction to Operators” course. The order of the operators demos that instructor Eitan introduced in the video is Prometheus, PostgreSQL, and then Cert Manager, however, the lesson order in the course is 4a-Postgres Operator, 4b-Cert Manager, and then 4c-Prometheus which does not match the information shared in the video. It’s not a big issue but just curious why the order is different in the video and course. 

https://staging.kubeacademy.fixeldev.com/courses/introduction-to-operators/lessons/lesson-4-intro-to-using-operators

<img width="980" alt="image" src="https://user-images.githubusercontent.com/48082421/163094815-2be64a27-3e35-4505-94b8-d2e1fddea14f.png">

**Comment by djschny** [comment]
Thanks for reporting! This is a known issue - https://github.com/kube-academy/backlog/issues/81

The order is supposed to be as listed in the outline as it was intentional to start with the PostgreSQL operator first. The recordings were not supposed to reference any order so that we were free to include, exclude, or re-order as desired, unfortunately when the author recorded them they still put the wording of saying order in the recordings.

See https://github.com/kube-academy/backlog/issues/76 for more context as well.

I hope that explains why it's the way it is and why we have focused time/effort in other areas. The author that did the recordings is no longer with VMware as well, so we need to either edit or re-record.

**Comment by hosseinpn** [comment]
Tracking via the KA issue #81
