### ISSUE TITLE
Consider adding TKO HOL into our TKO Training

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#47]
**Why would you like this feature?**
There is a new HOL that was created by Kevin Brady that may be worth adding

**Describe what you'd like to see**
Consider including the following HOL: https://labs.hol.vmware.com/HOL/catalogs/lab/10414

**Comment by djschny** [comment]
Link to lab manual - https://docs.hol.vmware.com/HOL-2022/hol-2234-02-map_html_en/

Options discussed:

* Provide overview video prior (maybe 3 minutes or so) to give guidance on how best to manage/use the course
* Potentially could be the public version of a lab that uses vSphere since it is a public facing version that we aren't currently covered by Instruqt or H2O.

**Comment by djschny** [comment]
Potential next steps are investigation work of how we would add it:

* go through the lab as a learner and see more details about what is covered and what is overlap, what is new, etc.
* location wise would it go better before or after public cloud deployments (gut feeling says since AWS TKO is simpler than vSphere TKO might be better after that)
* What would go into the "guidance" video
* etc.

**Comment by ndwinton** [comment]
I've just taken a look at the content of this compared to the existing [TMC lab](https://labs.hol.vmware.com/HOL/catalogs/lab/10506) that we link out to from the "Product: Tanzu Mission Control (TMC) - Lab" lesson.

The newer HOL is a superset of the TMC lab and covers all of the same TMC material (and more) in addition to covering TKG, TO and TSM. I suggest that the flow of lessons should now be:

* What is TKO and why is it valuable? _video (8:30)_
* Product: Tanzu Kubernetes Grid  _video (9:00)_
* Product: Tanzu Mission Control _video (4:30)_
* Product: Tanzu Observability _video (3:00)_
* Product: Tanzu Service Mesh _video (40:00) --- although we could really do with something shorter!_
* TKO Hands-On Lab _HOL (1:30:00)_
* ... remainder of content ...

Alternatively, we could drop straight into the HOL after the initial intro.

The later "Test Drive" (via Pathfinder) might be unnecessary, although it does have the advantage of giving access to a real environment for a couple of days.

**Comment by djschny** [comment]
Given the removal of the "Demo" lesson and the fact that the Pathfinder TestDrive has more realistic resources and grants you access for 2 days, the approach being taken will add the HOL lab modules as lessons after each respective video. So for example:

* Product: Tanzu Kubernetes Grid video (9:00)
* Product: Tanzu Kubernetes Grid - Lab (60:00)
* Product: Tanzu Mission Control video (4:30)
* Product: Tanzu Mission Control - Lab (45:00)
* Product: Tanzu Observability video (3:00)
* Product: Tanzu Observability - Lab (15:00)
* Product: Tanzu Service Mesh video (2:45) updated with https://youtu.be/0-u3bCRS_6M from above
* Product: Tanzu Service Mesh - Lab (15:00)

We would **not** ask folks to take the following modules:

* Module  5 - Introduction to NSX Advanced Load Balancer (Avi)
* Module 7- Introduction to Harbor (15 minutes)

![image](https://user-images.githubusercontent.com/129643/190157308-887d1375-5afe-4f5e-8c05-69528a2db582.png)

**Comment by djschny** [comment]
The aforementioned changes have been done:

* https://staging.kubeacademy.fixeldev.com/courses/tanzu-for-kubernetes-operations-tko-products-and-components

![Screen Shot 2022-09-14 at 9 53 58 AM](https://user-images.githubusercontent.com/129643/190173555-8e7f30b2-cd9a-4a91-8fcc-e1370e38d651.png)

**Comment by ndwinton** [comment]
This scheme has overall worked successfully. However, the TSM content in the HOL isn not actually "hands on" at all. We may need to find some alternative (or ask people to wait for the "Test Drive" session.
